<a href="https://colab.research.google.com/github/InquietoPartho/Machine-Learning-Deep-Learning/blob/main/Complete_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

In [4]:
from time import process_time

#Difference between list and numpy by time taken

In [5]:
my_list = [i for i in range(1000)]

start_time  = process_time()

my_list = [i+5 for i in my_list]

end_time = process_time()

print(end_time - start_time)

0.0002442389999997019


In [6]:
#time measure in numpy array

array = np.array([i for i in range(1000)])

start_time = process_time()

arr =+5

end_time = process_time()

print(end_time - start_time)



0.00010887400000036962


In [7]:
np_array =np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

In [8]:
#creating one dimensional array

a = np.array([1,2,3,4,5])
print(a)
a.shape

[1 2 3 4 5]


(5,)

In [9]:
#multiple dimensioning array

b = np.array([(1,2,3,4),(5,6,7,8)])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [10]:
b.shape

(2, 4)

In [11]:
#Datatype
c = np.array([(1,2,3,4),(5,6,7,8)],dtype = float)
print(c)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


Initial Placeholder in numpy arrays

In [12]:
#create a numpy array of Zeros

In [13]:
x = np.zeros((4,4))
print(x)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [14]:
#create numpy array of ones
y = np.ones((3,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [15]:
#array of a particular value
z = np.full((5,4),5)
print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [16]:
#create an identity matrix

a = np.eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [19]:
#create a numpy array with random values

b  = np.random.random((3,4))
print(b)

[[0.96608746 0.88785169 0.84691001 0.05447038]
 [0.47610102 0.66698627 0.36957499 0.9936167 ]
 [0.65145784 0.78149919 0.37089186 0.03960523]]


In [20]:
#random interger values within a specific range
c = np.random.randint(10,100,(3,5))
print(c)

[[89 28 65 72 94]
 [53 27 23 63 68]
 [16 46 30 90 67]]


In [21]:
#array of evenly spaced values -->specifying the number of values required
d = np.linspace(10,30,5)
print(d)

[10. 15. 20. 25. 30.]


In [22]:
#array of evenly spaced values -->specifying the step

e = np.arange(10,30,5)
print(e)

[10 15 20 25]


In [23]:
#convert a list to a numpy array

list2 = [10,20,30,40,50]

np_array = np.array(list2)

print(np_array)
type(np_array)

[10 20 30 40 50]


numpy.ndarray

#Analysing a Numpy Array

In [24]:
c  = np.random.randint(10,90,(5,5))
print(c)

[[47 15 47 10 67]
 [53 26 19 38 31]
 [19 49 84 14 67]
 [69 23 44 46 40]
 [70 71 50 13 38]]


In [25]:
#array Dimensions
print(c.shape)

(5, 5)


In [26]:
#number of dimensions
print(c.ndim)

2


In [28]:
#checking the number of elements in an array
print(c.size)

25


In [29]:
#checking the datat types of values in the array
print(c.dtype)

int64


#mathemetical operation in numpy array

In [30]:
list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]

print(list1+list2)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [31]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))

In [32]:
print(a)
print(b)

[[1 9 0]
 [2 2 4]
 [3 6 1]]
[[13 19 14]
 [15 17 18]
 [10 18 19]]


In [34]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[14 28 14]
 [17 19 22]
 [13 24 20]]
[[-12 -10 -14]
 [-13 -15 -14]
 [ -7 -12 -18]]
[[ 13 171   0]
 [ 30  34  72]
 [ 30 108  19]]
[[0.07692308 0.47368421 0.        ]
 [0.13333333 0.11764706 0.22222222]
 [0.3        0.33333333 0.05263158]]


In [35]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))

In [36]:
print (a)
print(b)

[[2 5 1]
 [7 2 4]
 [3 7 9]]
[[17 17 18]
 [13 14 16]
 [17 16 10]]


In [38]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[19 22 19]
 [20 16 20]
 [20 23 19]]
[[-15 -12 -17]
 [ -6 -12 -12]
 [-14  -9  -1]]
[[ 34  85  18]
 [ 91  28  64]
 [ 51 112  90]]
[[0.11764706 0.29411765 0.05555556]
 [0.53846154 0.14285714 0.25      ]
 [0.17647059 0.4375     0.9       ]]


#Array Manipulation

In [40]:
array = np.random.randint(0,10,(2,3))

print(array)
print(array.shape)

[[7 1 3]
 [4 6 7]]
(2, 3)


In [41]:
#Transpose

trans = np.transpose(array)
print(trans)
print(trans.shape)

[[7 4]
 [1 6]
 [3 7]]
(3, 2)


In [42]:
array = np.random.randint(0,10,(2,3))

print(array)
print(array.shape)

[[9 2 6]
 [8 2 8]]
(2, 3)


In [43]:
trans2 = array.T
print(trans2)
print(trans2.shape)

[[9 8]
 [2 2]
 [6 8]]
(3, 2)


In [45]:
#Reshaping array

a = np.random.randint(0,10,(2,3))
print(a)

[[2 0 5]
 [3 8 7]]


In [46]:
b = a.reshape(3,2)
print(b)

[[2 0]
 [5 3]
 [8 7]]


In [47]:
b.shape

(3, 2)