In [1]:
import numpy as np

In [2]:
matrix_1 = np.array([[1,2],[3,4]])

In [3]:
print(matrix_1)

[[1 2]
 [3 4]]


In [4]:
matrix_1.shape

(2, 2)

Matrix with random values

In [14]:
matrix_2 = np.random.rand(4,4) #all points are between 0 and 1 and floating points
print(matrix_2)


[[0.68910082 0.63399369 0.25799066 0.18125607]
 [0.17532345 0.34832751 0.6074963  0.53978145]
 [0.15359601 0.37664638 0.74661494 0.99697783]
 [0.54462312 0.69673404 0.45468146 0.24092186]]


Matrix with random integers

In [11]:
matrix_3 = np.random.randint(10,size = (4,4))
print(matrix_3)

[[6 9 5 1]
 [4 8 9 5]
 [3 0 1 7]
 [9 9 6 2]]


Null Matrix

In [23]:
null = np.zeros((4,4), dtype =int)
print(null)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [21]:
one =  np.ones((4,4))
print(one)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [22]:
one_1 = np.ones((4,4),dtype = int)
print(one_1)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


Identity Matrix

In [24]:
identity = np.eye(3,3)
print(identity)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Transpose of a matrix

In [25]:
a = np.random.randint(100,size = (5,5))
print(a)

[[18 54  1 44 49]
 [60 22  5 90 17]
 [97 16 94 65 80]
 [32 67 46 79 97]
 [44 14 25 42 14]]


In [26]:
transpose_a = np.transpose(a)
print(transpose_a)

[[18 60 97 32 44]
 [54 22 16 67 14]
 [ 1  5 94 46 25]
 [44 90 65 79 42]
 [49 17 80 97 14]]
